[package]
name = "tigtag"
version.workspace = true
edition.workspace = true

[workspace.package]
version = "0.18.0"
edition = "2024"

[[bin]]
name = "tigtag"
path = "crates/tigtag/src/main.rs"

[features]
sprite_off = [] #スプライト画像の代わりにプリミティブシェイプを表示するコンパイルスイッチ
attach_viewport = [] #cameraにviewportをセットするコンパイルスイッチ

################################################################################

[dependencies]
bevy.workspace = true
rand.workspace = true
getrandom.workspace = true
chrono.workspace = true
macros.workspace = true

[workspace.dependencies]
#Bevyのバージョン／ブランチ等の指定
#bevy = { git = "https://github.com/bevyengine/bevy", features = [ # Master branch
#bevy = { git = "https://github.com/bevyengine/bevy", tag = "v0.15.0-rc.3", features = [
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "release-0.14.0", features = [

#bevy = { version = "=0.18.0-rc.2", features = ["bevy_ui_debug"] }
#bevy = { version = "0.18", features = ["bevy_ui_debug"] }
bevy = { version = "0.18", default-features = false, features = [
    "bevy_ui_debug",
#   "ui",
    "2d",
#   "3d",
] }

#依存するその他のcrate
rand = "0.9"
getrandom = { version = "0.3", features = [ "wasm_js" ] } #wasmコンパイル時のエラー対策
chrono = "0.4"

#マクロ関係の依存
macros        = { path = "crates/macros"        }
macros_inside = { path = "crates/macros_inside" }
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

################################################################################

#releaseプロファイル
[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

#developプロファイル
[profile.dev.package."*"]
opt-level = 3

#wasm releaseプロファイル
[profile.release-wasm]
inherits = "release"
opt-level = "s"
debug = "none"
#split-debuginfo = "packed" #platform-specific
strip = "symbols"
#lto = true #モバイルブラウザで表示されない不具合の対策
codegen-units = 1
panic = "abort"

#wasm developプロファイル
[profile.dev-wasm]
inherits = "dev"
opt-level = "s"
debug = "none"
#split-debuginfo = "packed" #platform-specific
strip = "symbols"
#lto = true #モバイルブラウザで表示されない不具合の対策
codegen-units = 1
panic = "abort"
